# 作業

思考一下我們前面有提到圖片是矩陣，但維度可能會不一樣
例如灰階圖只有兩個維度，RGB 彩圖則有 3 個維度

假如今天我們把 RGB 3 個維度拆開來看會有甚麼不同的效果呢？

In [2]:
import numpy as np
import cv2

In [23]:
img_path = 'D01-data/Part01/lena.png'
# 以彩色圖片的方式載入
img=cv2.imread(img_path, cv2.IMREAD_COLOR) #cv2.IMREAD_COLOR:彩色 / cv2.IMREAD_GRAYSCALE:灰階
type(img)

numpy.ndarray

In [24]:
#show lena原圖
#img=cv2.imshow('lena',img)
#cv2.waitKey(0) 
#cv2.destroyAllWindows()

In [25]:
print(img, sep = ",") 

[[[125 137 226]
  [125 137 226]
  [133 137 223]
  ...
  [122 148 230]
  [110 130 221]
  [ 90  99 200]]

 [[125 137 226]
  [125 137 226]
  [133 137 223]
  ...
  [122 148 230]
  [110 130 221]
  [ 90  99 200]]

 [[125 137 226]
  [125 137 226]
  [133 137 223]
  ...
  [122 148 230]
  [110 130 221]
  [ 90  99 200]]

 ...

 [[ 60  18  84]
  [ 60  18  84]
  [ 58  27  92]
  ...
  [ 84  73 173]
  [ 76  68 172]
  [ 79  62 177]]

 [[ 57  22  82]
  [ 57  22  82]
  [ 62  32  96]
  ...
  [ 79  70 179]
  [ 81  71 181]
  [ 81  74 185]]

 [[ 57  22  82]
  [ 57  22  82]
  [ 62  32  96]
  ...
  [ 79  70 179]
  [ 81  71 181]
  [ 81  74 185]]]


In [29]:
#保留B,把G和R設為0
img_B = img.copy() #B/G/R
img_B[:,:,1]=0 #G
img_B[:,:,2]=0 #R
#print(img_B, sep = ",") 

#show lena藍
img_B=cv2.imshow('lena_B',img_B)
cv2.waitKey(0) 
cv2.destroyAllWindows()

In [31]:
#保留G,把B和R設為0
img_G = img.copy() #B/G/R
img_G[:,:,0]=0 #B
img_G[:,:,1]=0 #G
#print(img_G, sep = ",") 

#show lena綠
img_G=cv2.imshow('lena_G',img_G)
cv2.waitKey(0) 
cv2.destroyAllWindows()

In [27]:
#保留R,把B和G設為0
img_R = img.copy() #B/G/R
img_R[:,:,0]=0 #B
img_R[:,:,1]=0 #G
#print(img_R, sep = ",") 

#show lena紅
img_R=cv2.imshow('lena_R',img_R)
cv2.waitKey(0) 
cv2.destroyAllWindows()